### ISSUE TITLE
FileNotFoundError

### ISSUE THREAD

**Issue by Jacky117** [qiandeng1/yobot_ImageEngine#1]
如图，components中找不到test文件
![999](https://github.com/qiandeng1/yobot_ImageEngine/assets/107171157/bc89d886-6a84-4340-abd3-b28ef2505d48)

**Comment by qiandeng1** [comment]
你是不是用的git clone方式拷贝到本地的。。github上的源码我忘记屏蔽这段了。。
解决方法暂时能用这俩方法
1、用Releases里的
2、在yobot\src\client\ybplugins\clan_battle\components\imageEngine路径下创建一个test文件夹应急

后面会修复这个问题，这是我当时debug留下的忘记删了hhh

**Comment by Jacky117** [comment]
随便放了张图片进去，可以正常运行了
