### ISSUE TITLE
求助：生成图片报错

### ISSUE THREAD

**Issue by 964788339** [qiandeng1/yobot_ImageEngine#2]
![image](https://github.com/qiandeng1/yobot_ImageEngine/assets/61876981/30f26673-bbbe-42cd-a691-bdfc7a55d151)

**Comment by qiandeng1** [comment]
你查看一下yobot_remix/src/client/ybplugins/clan_battle/components/imageEngine/monster_icon路径下的data.json，不出意外应该是ID号为4003的boss中文名称不对，改成"水晶闪耀之龙"就好了

**Comment by qiandeng1** [comment]
应该会在下一个版本更新的时候顺便修复。问题解决了的话记得关闭

**Comment by 964788339** [comment]
感谢！
